package dev.lui.huaweisync.ui.theme

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

/** Semantic palette for the approved Calm Health Companion direction. */
@Immutable
data class HuaweiSyncColors(
    val background: Color,
    val surface1: Color,
    val surface2: Color,
    val surface3: Color,
    val surfaceAccentWash: Color,
    val surfaceAttentionWash: Color,
    val ink: Color,
    val prototypeInk2: Color,
    val ink2: Color,
    val ink3: Color,
    val ink4: Color,
    val line: Color,
    val lineStrong: Color,
    val canvasBackground: Color,
    val accent: Color,
    /** Accent as readable foreground on neutral surfaces. */
    val accentForeground: Color,
    val accentContainer: Color,
    val accentSoft: Color,
    val accentSubtle: Color,
    val ok: Color,
    val warning: Color,
    val info: Color,
    val success: Color,
    val attention: Color,
    val error: Color,
    val neutralHigh: Color,
    val neutralLow: Color,
)

val DarkHuaweiSyncColors = HuaweiSyncColors(
    background = Color(0xFF0F1210),
    surface1 = Color(0xFF171A18),
    surface2 = Color(0xFF1F2321),
    surface3 = Color(0xFF262A28),
    surfaceAccentWash = Color(0x147CCFA5),
    surfaceAttentionWash = Color(0x1FE7A356),
    ink = Color(0xFFF4F5F1),
    prototypeInk2 = Color(0xFFB8BAB5),
    ink2 = Color(0xFFB8BAB5),
    ink3 = Color(0xFF989B95),
    ink4 = Color(0x667C7E79),
    line = Color(0xFF2F3330),
    lineStrong = Color(0xFF454A46),
    canvasBackground = Color(0xFF0F1210),
    accent = Color(0xFF7CCFA5),
    accentForeground = Color(0xFF7CCFA5),
    accentContainer = Color(0xFF244B39),
    accentSoft = Color(0xFF1F2E27),
    accentSubtle = Color(0x147CCFA5),
    ok = Color(0xFF7CCFA5),
    warning = Color(0xFFE7A356),
    info = Color(0xFF9FC9FF),
    success = Color(0xFF7CCFA5),
    attention = Color(0xFFE7A356),
    error = Color(0xFFF2B8B5),
    neutralHigh = Color(0xFF454A46),
    neutralLow = Color(0xFF262A28),
)

val LightHuaweiSyncColors = HuaweiSyncColors(
    background = Color(0xFFF7F7F5),
    surface1 = Color(0xFFFFFFFF),
    surface2 = Color(0xFFF1F1EE),
    surface3 = Color(0xFFE8E8E4),
    surfaceAccentWash = Color(0x142E7D5B),
    surfaceAttentionWash = Color(0x1FB26A00),
    ink = Color(0xFF12140F),
    prototypeInk2 = Color(0xFF545651),
    ink2 = Color(0xFF545651),
    ink3 = Color(0xFF6B6D68),
    ink4 = Color(0x6690918C),
    line = Color(0xFFE1E2DE),
    lineStrong = Color(0xFFC5C7C1),
    canvasBackground = Color(0xFFF7F7F5),
    accent = Color(0xFF2E7D5B),
    accentForeground = Color(0xFF2E7D5B),
    accentContainer = Color(0xFFC7E4D4),
    accentSoft = Color(0xFFE6F2EC),
    accentSubtle = Color(0x142E7D5B),
    ok = Color(0xFF2E7D5B),
    warning = Color(0xFF8A5200),
    info = Color(0xFF315F8E),
    success = Color(0xFF2E7D5B),
    attention = Color(0xFF8A5200),
    error = Color(0xFFB3261E),
    neutralHigh = Color(0xFFC5C7C1),
    neutralLow = Color(0xFFE8E8E4),
)
